### ISSUE TITLE
Wicked 1.0.0 portal-auth docker container can't resolve Portal and API hosts 

### ISSUE THREAD

**Issue by armezit** [Haufe-Lexware/wicked.haufe.io#150] opened 2018-12-24 13:02 UTC
_Host: Debian buster x64 (kernel: 4.18.0-3-amd64)
Docker: docker-ce version 18.09.0, build 4d60db4
Docker Compose: 1.22.0, build f46880fe_

When deploying wicked 1.0.0 to a docker host locally ([local machine without actual DNS entries](https://github.com/Haufe-Lexware/wicked.haufe.io/blob/wicked_1_0/doc/BETA.md#variant-1-deploying-to-your-local-machine-without-actual-dns-entries)), I faced with an error in all portal pages, which says:
```
{"error_description":"The access token is invalid or has expired","error":"invalid_token"}
```

and the screenshot:

![screenshot from 2018-12-24 15-56-13](https://user-images.githubusercontent.com/2006991/50399476-f5afbc80-0794-11e9-96f3-338886d8403a.png)

I looked at logs of the `portal-auth` container, and found these errors:

```
{"date":"2018-12-24T12:26:03.518Z","module":"portal-auth:generic-router","message":{"issueAsJson":false,"status":500,"oauthError":"server_error","internalError":{"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"api.portal.local","host":"api.portal.local","port":443}},"delta":587,"level":"error"}
{"date":"24/Dec/2018:12:26:03 +0000","method":"POST","url":"/auth/local/api/portal-api/token","remote-addr":"172.31.0.8","version":"1.1","status":"500","content-length":"92","referrer":"-","response-time":"124.893","correlation-id":"ef90fbd6-c934-43fa-97fa-99cd30f3cfbb"}
```

It seems that `portal-auth` DNS doesn't know anything about `portal.local` and `api.portal.local`. So I added these `extra_hosts` into the `docker-compose.yml` file under `portal-auth` service:
```
portal-auth:
    extra_hosts:
        - "portal.local:LOCAL_HOST_IP"
        - "api.portal.local:LOCAL_HOST_IP"
```

Rebuilt wicked docker containers and everything is fine!

I used the `docker-compose.yml` which was generated by `kickstarter`, without any modification.

I don't know if this error occurs when deploying to a docker host with real dns or not. 
Anyway, maybe it's better to add a comment about this in the deploying docs. or even a little change in kickstarter's generated docker-compose.yml file.

**Comment by DonMartin76** [comment] 2019-01-03 08:21
This is a duplicate of #149. Closing so that we can track in one place. Thanks for reporting!

**Closed by DonMartin76** 2019-01-03 08:21 UTC
