### ISSUE TITLE
Kickstarter should not be used to add API's

### ISSUE THREAD

**Issue by Krieke** [Haufe-Lexware/wicked.haufe.io#42] opened 2016-12-09 13:02 UTC
Why do we require kickstarter to add API's?  Since the Portal UI should be an interface on top of KONG one should be able to configure all KONG API supported features... not? So it would be better to add can configre API settings via the wicked Portal based on ADMIN rights or other group settings then each time building a new "static" dataset for the API that one wants to support.

**Comment by DonMartin76** [comment] 2016-12-09 14:48
Ah, yes, this is very much by design.

I do understand where you're coming from, but the design was made with CI/CD of everything in mind, which enables you to recreate an API deployment just from code, using the technique of immutable servers and configuration as code.

The only things which are not stored in the configuration repository are the data owned by the end users (aka developers) using the API portal. This is the dynamic configuration. Everything else is either deployment scripting or static configuration.

The kickstarter is the offline writing view on the API definitions. The portal API only reads the API definitions, but cannot change them.

**Comment by Krieke** [comment] 2016-12-12 06:57
Thanks for the answer... this gives us also the feedback that this tool can't be used within our design strategy.

**Comment by DonMartin76** [comment] 2016-12-12 08:15
Can I close this, or do you want to discuss your use case?

**Comment by DonMartin76** [comment] 2016-12-12 08:21
FWIW, I wrote a blog post on the new functionality in wicked 0.11.0: http://dev.haufe.com/updates-in-wicked-0-11/

This might contain additional useful information for you.

**Closed** 2016-12-29 13:22 UTC
Labels: question
