### ISSUE TITLE
kickstarter - volume permission problem inside container

### ISSUE THREAD

**Issue by trustlee** [Haufe-Lexware/wicked.haufe.io#53] opened 2017-01-25 19:27 UTC
The following permission problem is thrown when running with sudo or without.

...

docker run -it --rm -v /home/ec2-user/wickedconfigs:/var/portal-api -p 3333:3333 haufelexware/wicked.portal-kickstarter --new Assuming configuration path to be /var/portal-api.
Creating a new configuration directory...
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/var/portal-api/static'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.<anonymous> (/usr/src/app/bin/kickstart:70:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

**Comment by DonMartin76** [comment] 2017-01-26 20:21
Can you give me a couple of details? Which operating system? In the cloud (looks like AWS)? Running as root, or as a sudoer? How did you install docker?

I'd then try to reproduce.

**Comment by DonMartin76** [comment] 2017-02-13 19:56
Implementing a workaround for Linux in the next version. You will be able to specify a `LOCAL_UID` and a `LOCAL_GID` which are subsequently used inside the container, and the kickstarter will also run as this (freshly created) user.

**Comment by DonMartin76** [comment] 2017-02-13 21:00
I hope this is fixed now. Can you please give it a spin as soon as 0.11.4 is out?

**Closed by DonMartin76** 2017-02-13 21:00 UTC

**Comment by trustlee** [comment] 2017-02-15 15:59
Martin,

Sorry for the delay. Thanks for the follow-up!

Just confirming for you that error no longer appears at docker-compose startup.

 

On another basic matter (which may be a user error so I haven't created an issue)... if I simply

wget https://portal.local
--2017-02-15 10:57:18--  https://portal.local/
Resolving portal.local (portal.local)... 127.0.0.1
Connecting to portal.local (portal.local)|127.0.0.1|:443... connected.
Unable to establish SSL connection.

 

Or using curl:

curl https://portal.local

or

curl https://localhost:443

or

curl https://actual.ip.add.ress:433

I get:

 curl: (35) Encountered end of file


 

Is there TLS versioning things going on, or perhaps I've skipped some basic config?


Sent: Monday, February 13, 2017 at 4:00 PM

**Comment by DonMartin76** [comment] 2017-02-15 17:43
Hm, check the logs of the load balancer container (`publb`) to see whether you see something suspicious. What type of certificates are you using?

I am using dockercloud/haproxy:1.5.3 on a single docker host running Ubuntu 16 LTS for wicked-demo.haufe.io, so it does work in principle.

Which docker version are you using locally, which operating system?
