### ISSUE TITLE
Login/registration broken in localdev

### ISSUE THREAD

**Issue by ehirsch** [Haufe-Lexware/wicked.haufe.io#72] opened 2017-06-20 15:24 UTC
I have been following the documentation to setup a local wicked. Everything works like a charm! Until - I try to login. 

Any attempt to login with the default admin user will result in the login page being shown again. When navigation away from the login page I am actually login. But now it is not possible to logout again…

Something is terrible off. (It all worked yesterday - I just recreated the setup step by step).

I am using the 'latest' tag so `0.11.6` is probably the version.

OS: **macOS** (10.12.5)
Browser: **Chrome** and **Safari** both current (59.0.3071.86 and 10.1.1)

**Comment by DonMartin76** [comment] 2017-06-20 16:08
I can reproduce this on macOS 10.12 currently. I can't yet tell exactly what's wrong, will come back with more information as soon as I know more. It may have to do with the self signed certificates. Can you please also add operating system and the browser (and version) you are using?

Thanks for reporting!

**Comment by DonMartin76** [comment] 2017-06-21 05:38
Everything works as intended when using (a) real DNS names, and (b) valid certificates (e.g. from Let's Encrypt, see https://wicked-demo.haufe.io), so this has either something to do with the certificates, or some DNS lookup hiccup when using `/etc/hosts`.

**Comment by achwie** [comment] 2017-06-23 10:11
I've encountered a similar problem to Eike. For me the login didn't work randomly, but could be "fixed" by restarting the portal / portal-api services. Therefore to me it doesn't look like a config/cert issue.

**Comment by ehirsch** [comment] 2017-06-27 13:50
Any new insights? Can I help with anything?

**Comment by achwie** [comment] 2017-07-14 14:57
It seems like the user is authenticated correctly by the `portal-api` service. But somehow the auth info (user) is not transferred to the signup page during the success redirect to `/signup` (in `passport/lib/authenticate.js:241`). As far as I understand, this leads to the signup page not seeing the user as authenticated, because it expects the user object in the `request` but it's not there.

**Comment by DonMartin76** [comment] 2017-07-18 09:33
I have actually found the culprit. It's the update of `write-file-atomic` from 1.3.1 to 1.3.4 which seems to have broken it (end of April/beginning of May). I will pin it to 1.3.1 for the time being and notify the maintainer of `session-file-storage` to do something about it.

**Comment by ehirsch** [comment] 2017-07-18 13:56
Oh boy - the joy of the node ecosystem…
Good catch thou!

**Comment by DonMartin76** [comment] 2017-07-18 21:09
Fixed in 0.11.7.

**Closed by DonMartin76** 2017-07-18 21:09 UTC
Labels: bug, help wanted, priority: HIGH
